language: node_js
node_js:
  - "8"
  - "6"
os:
  - linux
  - osx
cache:
  directories:
  - node_modules
script:
  - npm run lint
  - npm test
notifications:
  email:
    on_success: never
    on_failure: change
after_success:
  - npm install nyc codecov
  - ./node_modules/.bin/nyc report --temp-directory=coverage --reporter=text-lcov | ./node_modules/.bin/coveralls
  - codecov -f coverage/*.json