env:
  global:
    - CC_TEST_REPORTER_ID=6e29e242a132576d8a09cd15dbbee62ffa903ebbe10ec73b4e689ba73481b6d9
language: node_js
node_js:
  - "8"
  - "6"
os:
  - linux
  - osx
cache:
  directories:
  - node_modules
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run lint
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email:
    on_success: never
    on_failure: change
after_success:
  - npm install nyc codecov
  - ./node_modules/.bin/nyc report --temp-directory=coverage --reporter=text-lcov | ./node_modules/.bin/coveralls
  - codecov -f coverage/*.json